---
title: "BH-adj"
output: html_document
date: "2024-04-07"
---
```{r}
#### Adjust all pvalues with BH procedure ####
rm(list=ls())
library(boxr)
library(dplyr)
library(ggplot2)
library(ggcorrplot)
library(gridExtra)

library(devtools)
#install_github("ben-arnold/washb")
library(tidyverse)
library(haven)
library(washb)
library(tmle)
library(foreign)
library(data.table)
library(devtools)
library(kableExtra)
library(here)
library(boxr)
library(here)

```

```{r}
H1_res <- readRDS('results/unadjusted/H1_res.RDS')
H3_res <- readRDS('results/unadjusted/H3_res.RDS')

H1_adj_res <- readRDS('results/adjusted/H1_adj_res.RDS')
H3_adj_res <- readRDS('results/adjusted/H3_adj_res.RDS')

H1_res$H = 1
H3_res$H = 3

H1_adj_res$H = 1
H3_adj_res$H = 3


full_res <- rbind(H1_res, H3_res)
full_adj_res <- rbind(H1_adj_res, H3_adj_res)
```

```{r}
full_res <- full_res %>% group_by(H) %>% 
  mutate(BH.Pval=p.adjust(Pval, method="BH")) %>%
  ungroup() %>%
  as.data.frame()

full_adj_res <- full_adj_res %>% group_by(H) %>% 
  mutate(BH.Pval=p.adjust(Pval, method="BH")) %>%
  ungroup() %>%
  as.data.frame()

saveRDS(full_res %>% filter(H==1) %>% select(-H), "results/unadjusted/H1_BH_res.RDS")
saveRDS(full_res %>% filter(H==3) %>% select(-H), "results/unadjusted/H3_BH_res.RDS")

saveRDS(full_adj_res %>% filter(H==1) %>% select(-H), "results/adjusted/H1_BH_adj_res.RDS")
saveRDS(full_adj_res %>% filter(H==3) %>% select(-H), "results/adjusted/H3_BH_adj_res.RDS")
```



