---
title: "Hypothesis 1"
output: html_document
date: "2024-03-27"
---


```{r}

library(boxr)
library(dplyr)
library(ggplot2)
library(ggcorrplot)
library(gridExtra)

library(devtools)
#install_github("ben-arnold/washb")

library(here)
#source("0-config.R")

library(tidyverse)
library(haven)
library(washb)
library(tmle)
library(foreign)
library(data.table)
library(devtools)
library(kableExtra)
library(here)
library(boxr)

directory <-  "/Users/xianshengyan/pregnancy-eed/"
setwd(directory)

```

```{r}

# Construct the path to the RDS file directly within the project folder
data_path <- "bangladesh-cleaned-master-data.RDS"

# Read the data from the RDS file
d <- readRDS(data_path)

```


```{r}
#Hypothesis 1 Variables

Xvars <- c("ln_preg_cort")
Yvars <- c("ln_mpo1", "ln_mpo2", "ln_mpo3", "ln_aat1", "ln_aat2", "ln_aat3", "ln_neo1", "ln_neo2", "ln_neo3", "ln_reg2", "ln_L_conc_t1", "ln_L_conc_t2", "ln_L_conc_t3", "ln_M_conc_t1", "ln_M_conc_t2", "ln_M_conc_t3")
```



```{r}
H1_models <- NULL
for(i in Xvars){
  for(j in Yvars){
    res_unadj <- fit_RE_gam(d=d, X=i, Y=j,  W=NULL)
    res <- data.frame(X=i, Y=j, fit=I(list(res_unadj$fit)), dat=I(list(res_unadj$dat)))
    H1_models <- bind_rows(H1_models, res)
  }
}
```

```{r}
#Get primary contrasts
H1_res <- NULL
for(i in 1:nrow(H1_models)){
  res <- data.frame(X=H1_models$X[i], Y=H1_models$Y[i])
  if(grepl("_def", H1_models$X[i])){
    preds <- predict_gam_diff(fit=H1_models$fit[i][[1]], d=H1_models$dat[i][[1]], quantile_diff=c(0.25,0.75), Xvar=res$X, Yvar=res$Y, binary=T)
  }else{
    preds <- predict_gam_diff(fit=H1_models$fit[i][[1]], d=H1_models$dat[i][[1]], quantile_diff=c(0.25,0.75), Xvar=res$X, Yvar=res$Y)
  }
  H1_res <-  bind_rows(H1_res , preds$res)
}

```

```{r}
#Make list of plots
H1_plot_list <- NULL
H1_plot_data <- NULL
for(i in 1:nrow(H1_models)){
  res <- data.frame(X=H1_models$X[i], Y=H1_models$Y[i])
  simul_plot <- gam_simul_CI(H1_models$fit[i][[1]], H1_models$dat[i][[1]], xlab=res$X, ylab=res$Y, title="")
  H1_plot_list[[i]] <-  simul_plot$p
  H1_plot_data <-  rbind(H1_plot_data, data.frame(Xvar=res$X, Yvar=res$Y, adj=0, simul_plot$pred))
}


#Save models
saveRDS(H1_models, "models/H1_models.RDS")

#Save results
saveRDS(H1_res, "results/unadjusted/H1_res.RDS")


#Save plots
#saveRDS(H1_plot_list, here("figure-objects/H1_unadj_splines.RDS"))

#Save plot data
saveRDS(H1_plot_data, "figure-data/H1_unadj_spline_data.RDS")
```


```{r}
results <- readRDS("results/unadjusted/H1_res.RDS")
write_csv(results,"results/unadjusted/H1_res.csv")
```



[1] "ln_preg_cort"
[1] "ln_mpo"
d$ln_M_conc_t1
```

